pref("extensions.identicanotifier.interval",3);
pref("extensions.identicanotifier.popup-interval", 5);
pref("extensions.identicanotifier.popup", true);
pref("extensions.identicanotifier.autoClose", false);
pref("extensions.identicanotifier.togglePopup", "P,,accel shift");
pref("extensions.identicanotifier.insertURL", "L,,accel shift");
pref("extensions.identicanotifier.currentUser", "");
pref("extensions.identicanotifier.login", true);
pref("extensions.identicanotifier.sound", false);
pref("extensions.identicanotifier.soundFile", "");
pref("extensions.identicanotifier.session", "");
pref("extensions.identicanotifier.debug", false);
pref("extensions.identicanotifier.met", true);
pref("extensions.identicanotifier.safety", true);
pref("extensions.identicanotifier.health", true);
pref("extensions.identicanotifier.days", "7");
